name: smart_ebocr_capture
description: "网上国网电量明细截图工具"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.20.2
  permission_handler: ^12.0.1
  paddle_ocr_flutter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
